name: Build & package .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal
      - name: Package
        run: dotnet pack -c Release --no-restore --no-build
      - name: Upload EntityGraphQL packages
        uses: actions/upload-artifact@v4
        with:
          name: Nuget packages
          path: |
            src/EntityGraphQL/bin/Release/*.nupkg
            src/EntityGraphQL.AspNet/bin/Release/*.nupkg
