name: Build & package .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test -nodereuse:false --no-restore --verbosity normal
      - name: Package
        run: dotnet pack -c Release --no-restore
      - name: Upload EntityGraphQL packages
        uses: actions/upload-artifact@v3
        with:
          name: Nuget packages
          path: |
            src/EntityGraphQL/bin/Release/*.nupkg
            src/EntityGraphQL.AspNet/bin/Release/*.nupkg
